openapi: "3.0.0"

info:
  version: '0.0.1'
  title: 'Iceberg'
  description: 'A service for visualizing machine learning model performance and selecting thresholds'

paths:
  /multi/{id}:
    get:
      tags:
      - Multi class
      parameters:
      - $ref: '#/components/parameters/id'
      - $ref: '#/components/parameters/tid'
      - $ref: '#/components/parameters/aid'
      - $ref: '#/components/parameters/rid'
      description: Returns multi class model
      responses:
        '200':
          description: Multi class model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MultiClassModel'
  /multi/{id}/stats:
    get:
      tags:
        - Multi class
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/tid'
        - $ref: '#/components/parameters/aid'
        - $ref: '#/components/parameters/rid'
        - $ref: '#/components/parameters/from'
        - $ref: '#/components/parameters/to'
      description: Returns statistics for a multi class model
      responses:
        '200':
          description: Statistics for a multi class model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MultiClassModelStats'
  /multi/{id}/data:
    post:
      tags:
      - Multi class
      parameters:
      - $ref: '#/components/parameters/id'
      - $ref: '#/components/parameters/tid'
      - $ref: '#/components/parameters/aid'
      - $ref: '#/components/parameters/rid'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MultiClassDatum'
      description: Post data to the model
      responses:
        '200':
          description: 'Data accepted'
        '400':
          description: 'Data was invalid'

components:
  parameters:
    id:
      name: id
      in: path
      required: true
      description: The ID of the model
      schema:
        type: string
        example: Workflow.VAT
    tid:
      in: header
      name: "X-Tradeshift-TenantId"
      description: Your tradeshift tenant id
      required: true
      schema:
        type: string
        format: uuid
        example: "4e3843f6-5424-40a7-bb6d-684e4e9a27b9"
    aid:
      in: header
      name: "X-Tradeshift-ActorId"
      description: Your tradeshift actor id
      required: false
      schema:
        type: string
        format: uuid
        example: "4e3843f6-5424-40a7-bb6d-684e4e9a27b9"
    rid:
      in: header
      name: "X-Tradeshift-RequestId"
      description: Your tradeshift request id
      required: false
      schema:
        type: string
        format: uuid
        example: "4e3843f6-5424-40a7-bb6d-684e4e9a27b9"
    from:
      in: query
      required: true
      name: from
      description: From the specified date
      schema:
        type: string
        format: date
        example: "2018-07-21"
    to:
      in: query
      required: true
      name: to
      description: To the specified date
      schema:
        type: string
        format: date
        example: "2018-08-21"
  schemas:
    MultiClassModelStats:
      type: object
      properties:
        model:
          $ref: '#/components/schemas/MultiClassModel'
        samples:
          description: How many samples are in the selected period
          type: integer
          example: 1237
        classes:
          description: How many different classes were in the selected period
          type: integer
          example: 9
        points:
          type: array
          description: The various metrics computed at different thresholds
          items:
            type: object
            properties:
              threshold:
                description: The threshold values the metrics have been computed for
                type: number
                example: 0.42
              correct:
                description: The fraction of correct classifications
                type: number
                example: 0.63
              errors:
                description: The fraction of errors
                type: number
                example: 0.09
              abstentions:
                description: The fraction of abstentions
                type: number
                example: 0.28
              f1:
                description: The micro average F1 score
                type: number
                example: 0.78
              precision:
                description: The micro average precision
                type: number
                example: 0.87
              recall:
                description: The micro average recall
                type: number
                example: 0.67
              tpr:
                description: True positive rate
                type: number
                example: 0.67
              fpr:
                description: False positive rate
                type: number
                example: 0.76
    MultiClassModel:
      type: object
      properties:
        id:
          type: string
          example: "Workflow.VAT"
        threshold:
          type: number
          example: 0.45
        error_cost:
          type: number
          example: 10.0
        abstain_cost:
          type: number
          example: 2.0
        correct_cost:
          type: number
          example: 0.0
        tags:
          type: array
          items:
            type: string
          example:
          - "tenant:bd36b076-32b1-4b58-a520-05549c56b933"
          - "product:workflow"

    MultiClassDatum:
      type: object
      properties:
        correct:
          type: string
          description: The correct outcome of the model
          example: "StandardRated"
        predictions:
          description: The outcomes predicted by the model and their scores. The scores should be in [0-1] and sum to 1.0
          type: object
          additionalProperties:
            type: number
          example:
            StandardRated: 0.65
            ZeroRated: 0.23
            None: 0.12