logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  loggers:
    "com.tradeshift": DEBUG

server:
  applicationContextPath: /iceberg

database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: iceberg

  # the password
  password: secret

  # the JDBC URL
  url: jdbc:h2:./db/h2